spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nhahocduong?currentSchema=nhahocduong
    username: nhahocduong_admin
    password: nhahocduong#123
    driver-class-name: org.postgresql.Driver