name: Build and deploy book App to AWS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy book App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"

      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml
